services:
  db:
    image: mysql:8.0
    container_name: quiz_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_password
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: