# Generated by Django 5.1.4 on 2024-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizquestion_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_id',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
