# Generated by Django 5.1.4 on 2024-12-15 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quizquestion_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
