# Generated by Django 5.1.4 on 2024-12-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quizquestion_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizquestion',
            name='unique_question_id',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
