# Generated by Django 5.1.4 on 2024-12-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quizquestion_unique_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
